"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
def findTheDifference(s: str, t: str) -> str:

    s_dict = {}
    t_dict = {}
    diff = ''

    for i in t:
        if i not in t_dict:
            t_dict[i] = t.count(i)

    for i in s:
        if i not in s_dict:
            s_dict[i] = s.count(i)

    for i in t_dict:
        if i not in s_dict:
            diff = i
        elif t_dict[i] != s_dict[i]:
            diff = i

    return diff

def main():
    print(findTheDifference(s = "abcd", t = "abcde"))
    print(findTheDifference(s = "", t = "y"))

if __name__ == "__main__":
    main()