"""
3. Who's the best

We wanna figure out who has the best name. Fortunately we have a perfect ordering of names (generated by
a magical AI), and just need a way to understand what it spits out. Then print out the best one!
File format: a series of lines of the form Name1 > Name2
Output: one of three things:
1. if a name is better than all others, then that name
2. if multiple names could be the best, then "UNKNOWN"
3. if there's a contradiction (Name1 > Name2, but Name2 > Name1), then "INVALID"
"""
def best_name(filename : str) -> str:
    with open(filename, "r") as file:
        # create list of lists
        content = file.read()
        content = content.splitlines()
        updated_content = []
        for row in content:
            temp = []
            for i in row.split(" "):
                temp.append(i)
            updated_content.append(temp)
        # create dictionary housing the valid names as keys and the names they've beaten as their values
        names_dict = {}
        for row in updated_content:
            if row[0] not in names_dict:
                names_dict[row[0]] = [row[2]]
            elif row[2] not in names_dict[row[0]]:
                names_dict[row[0]].append(row[2])
        # create a list of all valid names
        names = [name for name in names_dict.keys()]
        # create a list of all names that have been beaten by other names
        names_to_remove = []
        for val in names_dict.values():
            for name in names:
                if name in val:
                    names_to_remove.append(name)
        # create a list whose values dervice from the comparison and difference between names and names_to_remove lists
        names_remaining = [name for name in names if name not in names_to_remove]
        # return the appropriate output based on the given conditions
        if not names_remaining:
            return "INVALID"
        elif len(names_remaining) > 1:
            return "UNKNOWN"
        return names_remaining[0]

test_cases = [
    "test_cases/3/input1.txt",
    "test_cases/3/input2.txt",
    "test_cases/3/input3.txt",
    "test_cases/3/input4.txt",
    "test_cases/3/input5.txt",
    "test_cases/3/input6.txt",
    "test_cases/3/input7.txt"
]

for test in test_cases:
    print(best_name(test))