"""
3. Who's the best
2 / 2
We wanna figure out who has the best name. Fortunately we have a perfect ordering of names (generated by
a magical AI), and just need a way to understand what it spits out. Then print out the best one!
File format: a series of lines of the form Name1 > Name2
Output: one of three things:
1. if a name is better than all others, then that name
2. if multiple names could be the best, then "UNKNOWN"
3. if there's a contradiction (Name1 > Name2, but Name2 > Name1), then "INVALID"
"""
def whose_the_best(filename: str):

    with open(filename, 'r') as file:
        read_content = file.read()
        result = ''
        if read_content:
            split_list = read_content.splitlines()
            content = []
            for row in split_list:
                temp = []
                for i in row.split(' '):
                    temp.append(i)
                content.append(temp)

        return result

                

def main():
    print(whose_the_best('q3_data/input1.txt')) # alice
    print(whose_the_best('q3_data/input2.txt')) # invalid
    print(whose_the_best('q3_data/input5.txt')) # elmer

if __name__ == "__main__":
    main()