"""
3. Who's the best

We wanna figure out who has the best name. Fortunately we have a perfect ordering of names (generated by
a magical AI), and just need a way to understand what it spits out. Then print out the best one!
File format: a series of lines of the form Name1 > Name2
Output: one of three things:
1. if a name is better than all others, then that name
2. if multiple names could be the best, then "UNKNOWN"
3. if there's a contradiction (Name1 > Name2, but Name2 > Name1), then "INVALID"
"""
def best_name(filename : str) -> str:
    pass

test_cases = [
    "test_cases/3/input1.txt",
    "test_cases/3/input2.txt",
    "test_cases/3/input3.txt",
    "test_cases/3/input4.txt",
    "test_cases/3/input5.txt",
    "test_cases/3/input6.txt",
    "test_cases/3/input7.txt"
]

for test in test_cases:
    print(best_name(test))