"""
3. Who's the best

We wanna figure out who has the best name. Fortunately we have a perfect ordering of names (generated by
a magical AI), and just need a way to understand what it spits out. Then print out the best one!
File format: a series of lines of the form Name1 > Name2
Output: one of three things:
1. if a name is better than all others, then that name
2. if multiple names could be the best, then "UNKNOWN"
3. if there's a contradiction (Name1 > Name2, but Name2 > Name1), then "INVALID"
"""
def best_name(filename : str) -> str:

    result = ''

    with open(filename, 'r') as file:

        read_content = file.read()

        if read_content:

            lines = read_content.splitlines()
            content = []
            names = {}

            for row in lines:
                content.append(row.split(' '))

            for row in content:
                if row[0] not in names:
                    names[row[0]] = [row[2]]
                elif row[2] not in names[row[0]]:
                    names[row[0]].append(row[2])

            for key, val in names.items():
                for sec_key, sec_val in names.items():
                    if key in names[sec_key]:
                        for v in val:
                            if v not in names[sec_key]:
                                names[sec_key].append(v)

            best_names = []

            for key, val in names.items():
                counter = 0
                for sec_key, sec_val in names.items():
                    if key in sec_val:
                        counter += 1
                        break
                if counter == 0:
                    best_names.append(key)

            if len(best_names) == 1:
                result = best_names[0]
            elif len(best_names) > 1:
                result = 'Unknown'
            else:
                result = 'Invalid'

    return result

def main():
    print(best_name("3/input1.txt"))
    print(best_name("3/input2.txt"))
    print(best_name("3/input3.txt"))
    print(best_name("3/input4.txt"))
    print(best_name("3/input5.txt"))
    print(best_name("3/input6.txt"))
    print(best_name("3/input7.txt"))

if __name__ == "__main__":
    main()