"""
3. Who's the best

We wanna figure out who has the best name. Fortunately we have a perfect ordering of names (generated by
a magical AI), and just need a way to understand what it spits out. Then print out the best one!
File format: a series of lines of the form Name1 > Name2
Output: one of three things:
1. if a name is better than all others, then that name
2. if multiple names could be the best, then "UNKNOWN"
3. if there's a contradiction (Name1 > Name2, but Name2 > Name1), then "INVALID"
"""
def best_name(filename : str) -> str:
    with open(filename, "r") as file:
        content = file.read().splitlines()
        updated_content = []
        for row in content:
            temp = []
            for i in row.split(" "):
                temp.append(i)
            updated_content.append(temp)
        names_info = {}
        for row in updated_content:
            if row[0] not in names_info:
                names_info[row[0]] = [row[2]]
            elif row[2] not in names_info[row[0]]:
                names_info[row[0]].append(row[2])
        all_names = []
        for name in names_info.keys():
            all_names.append(name)
        remove_names = []
        for values in names_info.values():
            for name in all_names:
                if name in values:
                    remove_names.append(name)
        best_names = []
        for name in all_names:
            if name not in remove_names:
                best_names.append(name)
        if not best_names:
            return "INVALID"
        elif len(best_names) > 1:
            return "UNKNOWN"
        return best_names[0]

test_cases = [
    "test_cases/3/input1.txt",
    "test_cases/3/input2.txt",
    "test_cases/3/input3.txt",
    "test_cases/3/input4.txt",
    "test_cases/3/input5.txt",
    "test_cases/3/input6.txt",
    "test_cases/3/input7.txt"
]

for test in test_cases:
    print(best_name(test))