"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
def find_the_difference(s : str, t : str) -> str:

    s = list(s)
    t = list(t)
    s.sort()
    t.sort()
    
    for i in s:
        t.remove(i)

    return t[0]

def main():
    print(find_the_difference(s = "abcd", t = "abcde"))
    print(find_the_difference(s = "", t = "y"))
    print(find_the_difference(s = 'a', t = 'aa'))

if __name__ == "__main__":
    main()